version: '3.8'
services:

 localstack:
  image: localstack/localstack
  container_name: localstack
#  networks:
#   - aws-localstack-network
  restart: always
  ports:
   - "4566-4599:4566-4599"
  environment:
   - SERVICES=s3,lambda,cloudformation,apigateway,dynamodb
   - DEBUG=true
   - DATA_DIR=/tmp/localstack/data
   - LAMBDA_EXECUTOR=local
   - LAMBDA_REMOTE_DOCKER=false
   - DOCKER_HOST=unix:///var/run/docker.sock
   - START_WEB=1
  volumes:
   - ../tmp:/tmp/localstack
   - "/var/run/docker.sock:/var/run/docker.sock"
#networks:
# aws-localstack-network:
#  name: aws-localstack-network
#  driver: bridge